[workspace]
resolver = "2"
members = [
    "host/interop",
    "host/leaf-e2e",
    "host/resource-500b-e2e",
    "host/lmao-server-rs",
    "crates/lma-identity",
    "crates/leaf-rns",
    "crates/radio-interface",
    "crates/lma-wire",
    "crates/lma-lxmf",
    "crates/leaf-resource",
    "crates/lma-framing",
    "crates/leaf-power",
    "crates/sx126x",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
