// Cardputer native client (ESP32-S3 + Cap LoRa-1262 SX1262, ESP-IDF).
//
// Native replacement for the MicroPython cardputer_client (PR1 = sensor node,
// no display): boots RTReticulum with the onboard SX1262 LoRa interface,
// persists an identity in NVS, announces lmao/cardputer + lxmf/delivery on the
// LMAO mesh, learns the server's delivery identity from its periodic announce,
// and every INTERVAL sends a SensorReport (die temp always; DHT20 humidity
// when a Grove sensor is attached) as a send-only LXMF message to the server.
//
// The chart/display receive path lands in a follow-up (PR2).
#include <cstdio>
#include <memory>
#include <string>

#include "esp_log.h"
#include "esp_timer.h"
#include "nvs_flash.h"
#include "nvs.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"

#include "rtreticulum/identity.h"
#include "rtreticulum/destination.h"
#include "rtreticulum/transport.h"
#include "rtreticulum/reticulum.h"
#include "lora_interface.h"
#include "lma_identity.h"
#include "lma_encoder.h"
#include "lxmf_send.h"
#include "die_temp.h"
#include "dht20.h"
#include "path_find.h"
#if __has_include("lmao_config.h")
#include "lmao_config.h"   // generated by build.sh (DEST_HASH/interval/sensor)
#endif

using namespace RNS;
static const char* TAG = "cardputer";

// Server LXMF delivery destination hash.  install_all bakes the live server
// hash in at build time via -DLMAO_DEST_HASH_HEX="..."; leave it empty to run
// in announce-only mode (no SensorReport sent) — mirrors DEST_HASH=None.
#ifndef LMAO_DEST_HASH_HEX
#define LMAO_DEST_HASH_HEX ""
#endif
static const char* DEST_HASH_HEX = LMAO_DEST_HASH_HEX;

// Interval between SensorReports (seconds).  Default 300 s matches the
// Sprout telemetry cadence; E2E patches it to 15 s.  Clamped to >= 10 s to
// avoid LoRa congestion — mirrors _min_interval in main.py.
#ifndef LMAO_INTERVAL_SECONDS
#define LMAO_INTERVAL_SECONDS 300
#endif
static const uint32_t INTERVAL_SECONDS = LMAO_INTERVAL_SECONDS > 10 ? LMAO_INTERVAL_SECONDS : 10;

// Optional Grove DHT20 humidity sensor (sensor_id 2 "%").  Leave 0 to send
// only the die temperature.  Sensor temperature is read but discarded —
// sensor_id 1 stays the die temp (test-main contract).
#ifndef LMAO_SENSOR_TYPE
#define LMAO_SENSOR_TYPE 0   /* 0 = none, 1 = DHT20 */
#endif

// Grove port pins (Cardputer ADV): SDA=GPIO21, SCL=GPIO22 (verified).
#define DHT20_SDA_PIN 21
#define DHT20_SCL_PIN 22

// Asset announces every 30 s (unchanged from the uReticulum client).
#define ANNOUNCE_INTERVAL_MS 30000UL

#define TICK_MS 1000UL

// hexstr is provided by the shared lma_identity module (firmware_common) —
// the same one the Sprout client uses (DRY, see firmware_common/).
using lma_identity::hexstr;

static SemaphoreHandle_t s_ident_lock = nullptr;
static Identity s_server_identity;                 // learned from the server announce
static bool s_have_server = false;

static void on_announce_cb(const Bytes& dh, const Identity& peer, const Bytes&) {
    ESP_LOGI(TAG, "<< announce dest=%s id=%s", hexstr(dh).c_str(),
             hexstr(peer.get_salt()).c_str());
    if (DEST_HASH_HEX[0] == '\0') return;   // no destination configured
    if (hexstr(dh) == std::string(DEST_HASH_HEX)) {
        if (s_ident_lock) xSemaphoreTake(s_ident_lock, portMAX_DELAY);
        s_server_identity = peer;
        s_have_server = true;
        if (s_ident_lock) xSemaphoreGive(s_ident_lock);
        ESP_LOGI(TAG, "server delivery identity learned");
    }
}

static void send_sensor_report(const Identity& my_identity, bool dht_ok) {
    if (DEST_HASH_HEX[0] == '\0') {
        ESP_LOGW(TAG, "No destination configured — not sending");
        return;
    }
    uint64_t now_ms = (uint64_t)(esp_timer_get_time() / 1000);
    uint64_t unix_s = 946684800ULL + (uint64_t)(esp_timer_get_time() / 1000000ULL); // ~2000-epoch offset
    uint32_t seq = (uint32_t)(now_ms % 100000U);

    std::vector<std::string> readings;

    // sensor_id 1 — ESP32 die temperature ("C"), always sent.
    float die = die_temp::read_celsius();
    if (!(die >= -60.0f && die <= 150.0f)) {
        ESP_LOGW(TAG, "die temp read failed (NAN) — skipping SensorReport");
        return;
    }
    readings.push_back(lma_encoder::encode_reading(1, die, "C", now_ms));
    ESP_LOGI(TAG, "die temp = %.1f C", (double)die);

    // sensor_id 2 — optional DHT20 humidity ("%"); on-sensor temperature is
    // read but discarded (contract: sensor_id 1 stays the die temp).
    if (LMAO_SENSOR_TYPE == 1) {
        float t = 0.0f, h = 0.0f;
        const bool ok = dht_ok && dht20::read(&t, &h);
        if (ok && h >= 0.0f && h <= 100.0f) {
            readings.push_back(lma_encoder::encode_reading(2, h, "%", now_ms));
            ESP_LOGI(TAG, "humidity = %.1f %%", (double)h);
        } else {
            ESP_LOGW(TAG, "DHT20 read failed — sensor_id 1 only");
        }
    }

    std::string sreport = lma_encoder::encode_sensor_report(
        hexstr(my_identity.get_salt()), seq, 3.7f, readings);
    std::string envelope = lma_encoder::encode_envelope(sreport);
    ESP_LOGI(TAG, "SensorReport env=%uB readings=%u",
             (unsigned)envelope.size(), (unsigned)readings.size());

    Destination my_delivery(my_identity, Type::Destination::OUT, Type::Destination::SINGLE,
                            "lxmf", "delivery");
    if (s_ident_lock) xSemaphoreTake(s_ident_lock, portMAX_DELAY);
    bool have = s_have_server;
    Identity srv = s_server_identity;
    if (s_ident_lock) xSemaphoreGive(s_ident_lock);
    if (!have) {
        ESP_LOGW(TAG, "server identity not learned yet — skipping LXMF send (awaiting server announce)");
        return;
    }
    Destination server_delivery(srv, Type::Destination::OUT, Type::Destination::SINGLE,
                                "lxmf", "delivery");
    ESP_LOGI(TAG, "server delivery hash=%s", hexstr(server_delivery.hash()).c_str());

    Bytes body = lxmf_send::build_body(my_delivery, server_delivery, my_identity,
                                       Bytes(envelope), Bytes("p:Envelope"), unix_s);
    Bytes frame = lxmf_send::opportunistic_frame(server_delivery, body);
    if (frame.empty()) { ESP_LOGW(TAG, "no opportunistic frame"); return; }
    ESP_LOGI(TAG, "TX LXMF frame %uB -> server", (unsigned)frame.size());
    Transport::broadcast(frame, nullptr);
}

extern "C" void app_main(void);

void app_main() {
    ESP_LOGI(TAG, "Cardputer native client starting (PR1 sensor node)");

    esp_err_t nv = nvs_flash_init();
    if (nv == ESP_ERR_NVS_NO_FREE_PAGES || nv == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        nvs_flash_erase();
        nvs_flash_init();
    }

    s_ident_lock = xSemaphoreCreateMutex();

    // Persistent identity (NVS): keep the same RNS identity across boots so
    // the node is a stable mesh peer and can be allow-listed on the server.
    // A fresh native identity is minted on first boot — its lxmf/delivery
    // hash must be added to the server's ALLOWED_CLIENTS (like Sprout's).
    // Shared with the Sprout client (firmware_common/lma_identity).
    Identity identity = lma_identity::load_or_create("cardputer");
    ESP_LOGI(TAG, "identity hash: %s", hexstr(identity.get_salt()).c_str());
    {
        // The server allow-lists the sender's lxmf/delivery hash — print ours
        // so it can be added to ALLOWED_CLIENTS / LMAO_ALLOWED_CLIENTS.
        ESP_LOGI(TAG, "my lxmf/delivery hash: %s (add to server ALLOWED_CLIENTS)",
                 lma_identity::delivery_hash(identity).c_str());
    }

    auto lora = Cardputer::LoraInterface::create();
    if (!lora->start()) {
        ESP_LOGE(TAG, "LoRa interface failed to start, halting");
        while (true) vTaskDelay(pdMS_TO_TICKS(1000));
    }
    Transport::register_interface(lora);
    vTaskDelay(1);  /* yield to feed watchdog after LoRa init */

    // Sensors.
    if (!die_temp::init()) {
        ESP_LOGW(TAG, "die temp init failed");
    }
    bool dht_ok = false;
    if (LMAO_SENSOR_TYPE == 1) {
        dht_ok = dht20::init(DHT20_SDA_PIN, DHT20_SCL_PIN);
        ESP_LOGI(TAG, "DHT20 %s", dht_ok ? "present" : "absent — die temp only");
    }

    // Node + delivery destinations (IN) — announced so the server's LXMF
    // get_source() can resolve our delivery hash and allow-list the sender.
    Destination dest(identity, Type::Destination::IN, Type::Destination::SINGLE,
                     "lmao", "cardputer");
    Transport::register_destination(dest);
    ESP_LOGI(TAG, "dest hash: %s", hexstr(dest.hash()).c_str());

    Destination delivery(identity, Type::Destination::IN, Type::Destination::SINGLE,
                         "lxmf", "delivery");
    Transport::register_destination(delivery);
    ESP_LOGI(TAG, "delivery dest hash: %s", hexstr(delivery.hash()).c_str());

    Transport::on_announce(on_announce_cb);

    if (!Reticulum::start(100, 8192, 5)) {
        ESP_LOGE(TAG, "Reticulum::start failed");
        return;
    }

    ESP_LOGI(TAG, "send interval: %us, DEST_HASH: %s",
             (unsigned)INTERVAL_SECONDS, DEST_HASH_HEX[0] ? "configured" : "none (no sends)");

    uint64_t last_send_ms = 0;
    uint32_t last_announce_ms = 0;

    for (;;) {
        const uint32_t now_ms = (uint32_t)(esp_timer_get_time() / 1000);

        if (last_announce_ms == 0 || now_ms - last_announce_ms >= ANNOUNCE_INTERVAL_MS) {
            last_announce_ms = now_ms;
            dest.announce(Bytes(), true);
            delivery.announce(Bytes(), true);
            ESP_LOGI(TAG, "announced");

            // On-demand path discovery (issue #135): if the server identity is
            // not learned yet, ask the mesh for a path to the server's
            // lxmf/delivery destination instead of waiting for the server's
            // periodic announce.  path_find::request() is rate-limited (~20 s).
            if (s_ident_lock) xSemaphoreTake(s_ident_lock, portMAX_DELAY);
            const bool have_srv = s_have_server;
            if (s_ident_lock) xSemaphoreGive(s_ident_lock);
            if (!have_srv) path_find::request(DEST_HASH_HEX);
        }

        // Telemetry: first send immediately after boot, then every interval.
        if (last_send_ms == 0 || now_ms - last_send_ms >= (uint64_t)INTERVAL_SECONDS * 1000) {
            last_send_ms = now_ms;
            send_sensor_report(identity, dht_ok);
        }

        // Radio poll must stay on the main task (single-threaded SPI).
        lora->poll();

        vTaskDelay(pdMS_TO_TICKS(TICK_MS));
    }
}
