"""LMA Core — shared protobuf wrapper library.

Re-exports generated protobuf stubs for LMAO message types.
gRPC transport types are in ``lma_core.grpc_types`` and are
re-exported here for backward compatibility.

Requires protobuf stubs generated by either:
    bazel build //proto:lma_py_proto
or  python -m grpc_tools.protoc -I proto --python_out=proto --grpc_python_out=proto proto/lma.proto

Set PYTHONPATH to repo root when running outside Bazel.
"""

import logging

_logger = logging.getLogger(__name__)

try:
    from proto.lma_pb2 import (  # type: ignore[attr-defined]
        LMAOEnvelope,
        TextMessage,
        SensorReport,
        SensorReading,
        CommandRequest,
        CommandAck,
        AudioMessage,
        ImageMessage,
        CallSignal,
    )
except ImportError:
    _logger.critical(
        "Cannot import generated protobuf stubs from 'proto.lma_pb2'. "
        "Generate them with either:\n"
        "  Bazel:  bazel build //proto:lma_py_proto\n"
        "  Manual: protoc --python_out=. proto/lma.proto\n"
        "Then set PYTHONPATH to repo root when running outside Bazel."
    )
    raise

# gRPC transport types — imported lazily from lma_core.grpc_types
_grpc_available = False
try:
    from .grpc_types import (  # noqa: F401
        SendRequest,
        SendResponse,
        SubscribeRequest,
        SubscribeResponse,
        GetIdentityRequest,
        GetIdentityResponse,
        LMAOStub,
        LMAOServicer,
        LMAO,
        add_LMAOServicer_to_server,
    )

    _grpc_available = True
except ImportError:
    pass

__all__ = [
    # Core message types
    "LMAOEnvelope",
    "TextMessage",
    "SensorReport",
    "SensorReading",
    "CommandRequest",
    "CommandAck",
    "AudioMessage",
    "ImageMessage",
    "CallSignal",
]

# gRPC transport types (conditionally available)
if _grpc_available:
    __all__ += [
        "SendRequest",
        "SendResponse",
        "SubscribeRequest",
        "SubscribeResponse",
        "GetIdentityRequest",
        "GetIdentityResponse",
        "LMAOStub",
        "LMAOServicer",
        "LMAO",
        "add_LMAOServicer_to_server",
    ]
