"""LMA Core — shared protobuf wrapper library.

Re-exports generated protobuf stubs for LMAO message types.
Both the server and host-side tests import from this package.

Requires protobuf stubs generated by Bazel.  Run
    bazel build //proto:lma_py_proto
before importing this module outside Bazel.
"""

import logging

_logger = logging.getLogger(__name__)

try:
    from proto.lma_pb2 import (
        LMAOEnvelope,
        TextMessage,
        SensorReport,
        SensorReading,
        CommandRequest,
        CommandAck,
        AudioMessage,
        ImageMessage,
        CallSignal,
    )
except ImportError:
    _logger.critical(
        "Cannot import generated protobuf stubs from 'proto.lma_pb2'. "
        "This module requires protobuf stubs generated by Bazel. "
        "Run:  bazel build //proto:lma_py_proto  (or 'bazel build //...') "
        "before running the server or tests."
    )
    raise

__all__ = [
    "LMAOEnvelope",
    "TextMessage",
    "SensorReport",
    "SensorReading",
    "CommandRequest",
    "CommandAck",
    "AudioMessage",
    "ImageMessage",
    "CallSignal",
]
