#!/usr/bin/env bash
# Build the Sprout native firmware (issue #130, step 3) with ESP-IDF via Docker.
# Stages this repo's app into a fresh RTReticulum checkout (its
# components/rtreticulum wrapper compiles the RNS lib + ESP-IDF HAL), then
# builds for the ESP32-PICO-D4 target.
#
# One client, two device classes + per-plant match, chosen AT BUILD TIME:
#   --mode sprout       (default) full node: radio (DTU LoRa) + ENV III + upload
#   --mode sprout-lite  Atom Lite + Watering Unit only: moisture-only controller,
#                       no LoRa, no ENV III, no upload
#   --plant NAME        the plant profile baked as this device's default
#                       (kale herbs tomato succulent generic monstera; default kale)
# These are written into the STAGED main/device_config.h (the repo copy stays
# the sprout/kale default), so the built image IS the device configuration.
set -euo pipefail

# Device build configuration.
MODE="${SPROUT_MODE:-sprout}"
PLANT="${SPROUT_PLANT:-kale}"
TARGET="${SPROUT_TARGET:-esp32}"   # classic Atom Lite (esp32) | Atom Lite S3 (esp32s3)
while [ $# -gt 0 ]; do
    case "$1" in
        --mode)
            MODE="${2:-}"; shift 2 || true;;
        --plant)
            PLANT="${2:-}"; shift 2 || true;;
        --target)
            TARGET="${2:-}"; shift 2 || true;;
        -h|--help)
            echo "usage: $0 [--mode sprout|sprout-lite] [--plant NAME] [--target esp32|esp32s3]" >&2
            exit 0;;
        *)
            echo "unknown argument: $1" >&2
            echo "usage: $0 [--mode sprout|sprout-lite] [--plant NAME] [--target esp32|esp32s3]" >&2
            exit 2;;
    esac
done
if [ "$MODE" != sprout ] && [ "$MODE" != sprout-lite ]; then
    echo "invalid --mode '$MODE' (expected sprout or sprout-lite)" >&2
    exit 2
fi
case "$TARGET" in
    esp32|esp32s3) ;;
    *)
        echo "invalid --target '$TARGET' (expected esp32 or esp32s3)" >&2
        exit 2;;
esac
# The plant is resolved against the control engine's profile table at boot
# (control.cpp). Fail fast here on a typo instead of after flashing the device.
case "$PLANT" in
    kale|herbs|tomato|succulent|generic|monstera) ;;
    *)
        echo "unknown --plant '$PLANT' (known: kale herbs tomato succulent generic monstera)" >&2
        exit 2;;
esac

# Locate the firmware source dir.  `bazel run //smart_irrigation/native-client:build_firmware`
# exports BUILD_WORKSPACE_DIRECTORY; a direct `./build.sh` from this dir uses $0.
if [ -n "${BUILD_WORKSPACE_DIRECTORY:-}" ]; then
    APP="$BUILD_WORKSPACE_DIRECTORY/smart_irrigation/native-client/firmware"
else
    APP="$(cd "$(dirname "$0")" && pwd)"
fi
PARENT="$(dirname "$APP")"
RTR="$PARENT/.rtreticulum"
IDF_IMG="${IDF_IMG:-espressif/idf:v5.3.1}"

if [ ! -d "$RTR" ]; then
    echo "cloning RTReticulum -> $RTR"
    git clone -q --depth 1 https://github.com/0xSeren/RTReticulum "$RTR"
fi

DEST="$RTR/firmware/sprout"
mkdir -p "$DEST"
# Only remove our host-owned source dirs; the container (root) owns build/
# and ninja rebuilds deltas in place.
rm -rf "$DEST/main" "$DEST/components" 2>/dev/null || true
mkdir -p "$DEST/components"
cp -r "$APP/main" "$DEST/main"
# Bake the flash-time device config (mode + plant) into the staged source so
# `idf.py` compiles the right client variant; the repo copy of device_config.h
# stays the sprout/kale default.  flash.sh compares this staged header against
# its own --mode/--plant to detect a stale image before flashing.
if [ "$MODE" = sprout-lite ]; then
    LITE=1
else
    LITE=0
fi
{
    echo "// Generated by build.sh — device build config (flash-time)."
    echo "#define SPROUT_LITE $LITE"
    echo "#define SPROUT_PLANT \"$PLANT\""
} > "$DEST/main/device_config.h"
# Shared firmware component (firmware_common/): the protocol core both Sprout
# and the Cardputer client use (lma_encoder/lxmf_send/path_find/lma_identity)
# + the RTReticulum wrapper. Single canonical copy — no per-tree duplication.
cp -r "$APP/../../../firmware_common/lma_common" "$DEST/components/lma_common"
cp -r "$APP/../../../firmware_common/rtreticulum" "$DEST/components/rtreticulum"
cp "$APP/CMakeLists.txt" "$APP/sdkconfig.defaults" "$APP/partitions.csv" "$DEST/"
echo "app staged in $DEST (mode=$MODE plant=$PLANT target=$TARGET)"

docker run --rm -v "$RTR:/repo" -w /repo/firmware/sprout -e IDF_TARGET="$TARGET" \
    "$IDF_IMG" bash -lc "git config --global --add safe.directory /repo; idf.py set-target $TARGET && idf.py build" || exit 1
echo "Built: $DEST/build/sprout_native.bin (mode=$MODE plant=$PLANT target=$TARGET)"
