// Host unit test for the Sprout native SensorReport/LMAOEnvelope encoder.
//
// Golden bytes are generated by the reference Python encoder
// (cardputer_client/proto/lma_encoder.py) so the C++ port must produce
// byte-identical output (wire compatibility with the server's proto).
#include <cstdio>
#include <string>
#include <vector>

#include "lma_encoder.h"

static int failures = 0;

#define CHECK_EQ(actual, expected, label)                                    \
    do {                                                                     \
        std::string a = (actual);                                            \
        std::string e = std::string(expected);                               \
        if (a != e) {                                                        \
            std::printf("FAIL %s\n  actual  : '%s'\n  expected: '%s'\n",     \
                        label, a.c_str(), e.c_str());                        \
            failures++;                                                      \
        } else {                                                             \
            std::printf("ok   %s\n", label);                                 \
        }                                                                    \
    } while (0)

static std::string to_hex(const std::string& b) {
    static const char* H = "0123456789abcdef";
    std::string s;
    for (unsigned char c : b) {
        s.push_back(H[c >> 4]);
        s.push_back(H[c & 0x0f]);
    }
    return s;
}

int main() {
    using namespace lma_encoder;

    // Readings
    std::string rd_t = encode_reading(3, 25.5f, "C", 123456);
    std::string rd_h = encode_reading(2, 59.0f, "%", 123457);
    CHECK_EQ(to_hex(rd_t), "0803150000cc411a014320c0c407", "reading temp (id3)");
    CHECK_EQ(to_hex(rd_h), "08021500006c421a012520c1c407", "reading hum (id2)");

    // Soil moisture (id 4, %) — golden from cardputer_client/proto/lma_encoder.py.
    std::string rd_m = encode_reading(4, 35.0f, "%", 123458);
    CHECK_EQ(to_hex(rd_m), "08041500000c421a012520c2c407", "reading moist (id4)");

    // ONE SensorReport bundles air temp + humidity + soil moisture in the
    // same readings[] (the Sprout sensor bundle), all in one envelope.
    std::string rep3 = encode_sensor_report("a1b2c3", 7, 3.7f, {rd_t, rd_h, rd_m});
    CHECK_EQ(
        to_hex(rep3),
        "0a0661316232633310071dcdcc6c40220e0803150000cc411a014320c0c407"
        "220e08021500006c421a012520c1c407"
        "220e08041500000c421a012520c2c407",
        "sensor_report_3_readings");

    std::string env3 = encode_envelope(rep3);
    CHECK_EQ(
        to_hex(env3),
        "523f0a0661316232633310071dcdcc6c40220e0803150000cc411a014320c0c407"
        "220e08021500006c421a012520c1c407"
        "220e08041500000c421a012520c2c407",
        "lmao_envelope_3_readings");

    // SensorReport
    std::string rep = encode_sensor_report("a1b2c3", 7, 3.7f, {rd_t, rd_h});
    CHECK_EQ(
        to_hex(rep),
        "0a0661316232633310071dcdcc6c40220e0803150000cc411a014320c0c407"
        "220e08021500006c421a012520c1c407",
        "sensor_report");

    // LMAOEnvelope (field 10)
    std::string env = encode_envelope(rep);
    CHECK_EQ(
        to_hex(env),
        "522f0a0661316232633310071dcdcc6c40220e0803150000cc411a014320c0c407"
        "220e08021500006c421a012520c1c407",
        "lmao_envelope");

    if (failures == 0) {
        std::printf("ALL PASS\n");
        return 0;
    }
    std::printf("%d failure(s)\n", failures);
    return 1;
}
