//! LMAO control wire (design §5 `lma-wire`, ticket T5).
//!
//! Protobuf types generated **by prost from the shared `proto/lma_messages.proto`**
//! — not a hand-written second encoder — so a schema change lands everywhere at
//! once (design §6b). Cross-language equivalence with the Python reference
//! encoder (`cardputer_client/proto/lma_encoder.py`) is locked by the golden
//! vectors in `tests/`.
//!
//! Note: `std` — prost-generated code references `::std`; the leaf firmware
//! embeds these types where needed.

// Generated by prost-build from `proto/lma_messages.proto`.
include!(concat!(env!("OUT_DIR"), "/lma.rs"));

/// Build an `LmaoEnvelope` wrapping a `SensorReport` (field 10), ready for LXMF
/// `Content` — the leaf's control-path payload (T5).
pub fn sensor_envelope(
    node_id: &str,
    seq: u32,
    battery: f32,
    readings: Vec<SensorReading>,
) -> LmaoEnvelope {
    LmaoEnvelope {
        payload: Some(lmao_envelope::Payload::Sensor(SensorReport {
            node_id: node_id.to_owned(),
            seq,
            battery,
            readings,
        })),
    }
}

/// One canonical `SensorReading` (sensor_id per the shared registry in the proto).
pub fn reading(sensor_id: u32, value: f32, unit: &str, timestamp_ms: u64) -> SensorReading {
    SensorReading {
        sensor_id,
        value,
        unit: unit.to_owned(),
        timestamp_ms,
    }
}

/// RSSI measurement in dBm — sensor_id 9 per the proto registry (T9 “RSSI
/// reporting”; the leaf stamps the radio's RSSI on each received frame).
pub fn rssi_reading(value: f32, timestamp_ms: u64) -> SensorReading {
    reading(9, value, "dBm", timestamp_ms)
}
