//! Rust LMAO server — app layer.
//!
//! Ports the Python `lmao_server` app surface (design §5 / migration step 3):
//! gRPC `LMAO` service, SQLite contact book, contacts HTTP API, NATS
//! JetStream, and the LXMF delivery-handler logic. The RNS/LXMF mesh sits
//! behind [`delivery::MeshSender`], so the whole app layer is host-testable
//! without a radio.

pub mod contacts;
pub mod delivery;
pub mod grpc;
pub mod nats;
pub mod rf;
pub mod sprout;
pub mod store;

/// gRPC types + `LMAO` service (generated by tonic-build from `proto/lma_grpc.proto`).
pub mod lma {
    tonic::include_proto!("lma");
}
