# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import lma_pb2 as lma__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lma_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LMAOStub:
    """--- Service Definition ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/lma.LMAO/Send',
                request_serializer=lma__pb2.SendRequest.SerializeToString,
                response_deserializer=lma__pb2.SendResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/lma.LMAO/Subscribe',
                request_serializer=lma__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=lma__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.Tunnel = channel.stream_stream(
                '/lma.LMAO/Tunnel',
                request_serializer=lma__pb2.TunnelRequest.SerializeToString,
                response_deserializer=lma__pb2.TunnelResponse.FromString,
                _registered_method=True)
        self.GetIdentity = channel.unary_unary(
                '/lma.LMAO/GetIdentity',
                request_serializer=lma__pb2.GetIdentityRequest.SerializeToString,
                response_deserializer=lma__pb2.GetIdentityResponse.FromString,
                _registered_method=True)


class LMAOServicer:
    """--- Service Definition ---

    """

    def Send(self, request, context):
        """Send an envelope into the LXMF mesh.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe to incoming LXMF messages as a server-stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tunnel(self, request_iterator, context):
        """Bidirectional tunnel for raw LXMF packets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIdentity(self, request, context):
        """Get the server's Reticulum identity hash.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LMAOServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=lma__pb2.SendRequest.FromString,
                    response_serializer=lma__pb2.SendResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=lma__pb2.SubscribeRequest.FromString,
                    response_serializer=lma__pb2.SubscribeResponse.SerializeToString,
            ),
            'Tunnel': grpc.stream_stream_rpc_method_handler(
                    servicer.Tunnel,
                    request_deserializer=lma__pb2.TunnelRequest.FromString,
                    response_serializer=lma__pb2.TunnelResponse.SerializeToString,
            ),
            'GetIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentity,
                    request_deserializer=lma__pb2.GetIdentityRequest.FromString,
                    response_serializer=lma__pb2.GetIdentityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lma.LMAO', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lma.LMAO', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LMAO:
    """--- Service Definition ---

    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lma.LMAO/Send',
            lma__pb2.SendRequest.SerializeToString,
            lma__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lma.LMAO/Subscribe',
            lma__pb2.SubscribeRequest.SerializeToString,
            lma__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tunnel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/lma.LMAO/Tunnel',
            lma__pb2.TunnelRequest.SerializeToString,
            lma__pb2.TunnelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lma.LMAO/GetIdentity',
            lma__pb2.GetIdentityRequest.SerializeToString,
            lma__pb2.GetIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
