#!/usr/bin/env bash
# Build the Cardputer native firmware (PR1 — sensor node) with ESP-IDF via
# Docker.  Stages this repo's app into a fresh RTReticulum checkout (its
# components/rtreticulum wrapper compiles the RNS lib + ESP-IDF HAL), then
# builds for the ESP32-S3 target.
#
# Build-time injection (source tree never modified):
#   LMAO_DEST_HASH_HEX     server delivery hash (32 hex) — baked into the app
#   LMAO_INTERVAL_SECONDS  send interval (default 300, min clamped to 10)
#   LMAO_SENSOR_TYPE       0 = none, 1 = DHT20
# These are written into a generated lmao_config.h in the *staged* copy (under
# .rtreticulum/firmware/cardputer), mirroring how install_all used to patch a
# temp config.py for the MicroPython client.
set -euo pipefail
# Locate the firmware source dir.  `bazel run //cardputer_client:build_firmware`
# exports BUILD_WORKSPACE_DIRECTORY; a direct `./build.sh` from this dir uses $0.
if [ -n "${BUILD_WORKSPACE_DIRECTORY:-}" ]; then
    APP="$BUILD_WORKSPACE_DIRECTORY/cardputer_client/firmware"
else
    APP="$(cd "$(dirname "$0")" && pwd)"
fi
PARENT="$(dirname "$APP")"
# Reuse the repo's single pinned RTReticulum checkout (the one Sprout's
# native-client build uses, at the WORKSPACE-pinned commit) so the Cardputer
# firmware compiles against the same rev — never a drifting fresh clone.
SPROUT_RTR="$(cd "$APP/../../smart_irrigation/native-client" 2>/dev/null && pwd)/.rtreticulum"
RTR="${RTRETICULUM_ROOT:-}"
if [ -z "$RTR" ] && [ -d "$SPROUT_RTR" ]; then
    RTR="$SPROUT_RTR"
fi
RTR="${RTR:-$PARENT/.rtreticulum}"
IDF_IMG="${IDF_IMG:-espressif/idf:v5.3.1}"

if [ ! -d "$RTR" ]; then
    echo "cloning RTReticulum -> $RTR"
    git clone -q --depth 1 https://github.com/0xSeren/RTReticulum "$RTR"
fi

DEST="$RTR/firmware/cardputer"
mkdir -p "$DEST"
# Only remove our host-owned source dirs; the container (root) owns build/
# and ninja rebuilds deltas in place.
rm -rf "$DEST/main" "$DEST/components" 2>/dev/null || true
mkdir -p "$DEST/components"
cp -r "$APP/main" "$DEST/main"
# Shared firmware component (firmware_common/): the protocol core both the
# Sprout and Cardputer clients use (lma_encoder/lxmf_send/path_find/
# lma_identity) + the RTReticulum wrapper. Single canonical copy — no per-tree
# duplication.
cp -r "$APP/../../firmware_common/lma_common" "$DEST/components/lma_common"
cp -r "$APP/../../firmware_common/rtreticulum" "$DEST/components/rtreticulum"
cp "$APP/CMakeLists.txt" "$APP/sdkconfig.defaults" "$APP/partitions.csv" "$DEST/"
echo "app staged in $DEST"

# Generate the build-time config header in the staged copy (never the source).
HDR="$DEST/main/lmao_config.h"
{
    echo "// Generated by cardputer_client/firmware/build.sh — do not edit."
    echo "#pragma once"
    echo '#ifndef LMAO_DEST_HASH_HEX'
    if [ -n "${LMAO_DEST_HASH_HEX:-}" ]; then
        printf '#define LMAO_DEST_HASH_HEX "%s"\n' "$LMAO_DEST_HASH_HEX"
    else
        echo '#define LMAO_DEST_HASH_HEX ""'
    fi
    echo '#endif'
    echo '#ifndef LMAO_INTERVAL_SECONDS'
    echo "#define LMAO_INTERVAL_SECONDS ${LMAO_INTERVAL_SECONDS:-300}"
    echo '#endif'
    echo '#ifndef LMAO_SENSOR_TYPE'
    echo "#define LMAO_SENSOR_TYPE ${LMAO_SENSOR_TYPE:-0}"
    echo '#endif'
} > "$HDR"
echo "generated $HDR"

docker run --rm -v "$RTR:/repo" -w /repo/firmware/cardputer -e IDF_TARGET=esp32s3 \
    "$IDF_IMG" bash -lc 'git config --global --add safe.directory /repo; idf.py set-target esp32s3 && idf.py build' || exit 1
echo "Built: $DEST/build/cardputer_native.bin"
