#!/usr/bin/env bash
# codec2_prepare.sh — bring the upstream codec2 speech codec into an ESP-IDF
# component directory at build time (no upstream source is committed).
#
#   usage: codec2_prepare.sh <component-dir>     -> fills <component-dir>/codec2/
#
# Every file lands under <component-dir>/codec2/codec2/ exactly as the vendored
# layout the on-device verification used:
#   codec2/codec2/src/     the upstream src/ (188 files, byte-identical to the
#                          pinned commit: verified by diff)
#   codec2/codec2/codec2/version.h   build-generated by upstream cmake
#   codec2/codec2/inc/     empty (upstream ships no inc/)
# The 8 codebook*.c tables are upstream *generated* output (emit by running
# `generate_codebook` on the checked-in src/codebook/*.txt inputs) and are
# regenerated here — byte-identical apart from the embedded input path.
#
# Source selection (first match wins):
#   C2_SRC_DIR   an already-extracted upstream tree (bazel http_archive works)
#   C2_TARBALL   a local tarball of the pinned commit (bazel http_file)
#   default      download the pinned commit once into C2_CACHE_DIR (default
#                ~/.cache/lmao-codec2), verify sha256, reuse across builds.
set -euo pipefail

C2_COMMIT="b2311e5a967e09e5b293578bb596c83c50af536d"
C2_SHA256="aced7f60d8ffc2ce67f3ce8de345d1960362f83200c3fec1b83d38ef37aaad77"
C2_URL="https://github.com/drowe67/codec2/archive/${C2_COMMIT}.tar.gz"
DEST="${1:?usage: codec2_prepare.sh <component-dir>}"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# 1. obtain the upstream source -------------------------------------------
SRCTOP=""
if [ -n "${C2_SRC_DIR:-}" ] && [ -d "${C2_SRC_DIR}/src" ]; then
    SRCTOP="$C2_SRC_DIR"
elif [ -n "${C2_TARBALL:-}" ] && [ -f "$C2_TARBALL" ]; then
    tar xzf "$C2_TARBALL" -C "$WORK" --strip-components=1
    SRCTOP="$WORK"
else
    CACHE="${C2_CACHE_DIR:-$HOME/.cache/lmao-codec2}"
    mkdir -p "$CACHE"
    TAR="$CACHE/${C2_COMMIT}.tar.gz"
    if [ ! -f "$TAR" ]; then
        curl -fsSL -o "$TAR.tmp" "$C2_URL"
        echo "$C2_SHA256  $TAR.tmp" | sha256sum -c - >/dev/null
        mv "$TAR.tmp" "$TAR"
    fi
    tar xzf "$TAR" -C "$WORK" --strip-components=1
    SRCTOP="$WORK"
fi

# 2. lay out the component tree -------------------------------------------
C2="$DEST/codec2/codec2"
rm -rf "$C2"
mkdir -p "$C2/src" "$C2/codec2" "$C2/inc"
# -L: the bazel runfiles are symlinks into the bazel cache (absolute HOST
# paths); materialize real files so the staged component survives the Docker
# build mount (which doesn't see the host cache).
cp -rL "$SRCTOP/src/." "$C2/src/"

# 3. version.h — generated by upstream's cmake (cmake/version.h.in) at
#    CODEC2_VERSION 1.2.0; fixed here so the codec identifies 1.2.0.
cat > "$C2/codec2/version.h" <<'EOF'
#define CODEC2_VERSION_MAJOR 1
#define CODEC2_VERSION_MINOR 2
/* #undef CODEC2_VERSION_PATCH */
#define CODEC2_VERSION "1.2.0"
EOF

# 4. regenerate the codebook tables (upstream: src/CMakeLists.txt) --------
#    generate_codebook emits the C table for an array + one or more .txt
#    codebooks; compiled here on the host (upstream builds it too).
cc -O2 -o "$WORK/gen" "$C2/src/generate_codebook.c" -lm
D="$C2/src/codebook"
"$WORK/gen" lsp_cb \
    "$D/lsp1.txt" "$D/lsp2.txt" "$D/lsp3.txt" "$D/lsp4.txt" "$D/lsp5.txt" \
    "$D/lsp6.txt" "$D/lsp7.txt" "$D/lsp8.txt" "$D/lsp9.txt" "$D/lsp10.txt" \
    > "$C2/src/codebook.c"
"$WORK/gen" lsp_cbd \
    "$D/dlsp1.txt" "$D/dlsp2.txt" "$D/dlsp3.txt" "$D/dlsp4.txt" "$D/dlsp5.txt" \
    "$D/dlsp6.txt" "$D/dlsp7.txt" "$D/dlsp8.txt" "$D/dlsp9.txt" "$D/dlsp10.txt" \
    > "$C2/src/codebookd.c"
"$WORK/gen" lsp_cbjmv "$D/lspjmv1.txt" "$D/lspjmv2.txt" "$D/lspjmv3.txt" \
    > "$C2/src/codebookjmv.c"
"$WORK/gen" ge_cb "$D/gecb.txt" > "$C2/src/codebookge.c"
"$WORK/gen" newamp1vq_cb "$D/train_120_1.txt" "$D/train_120_2.txt" \
    > "$C2/src/codebooknewamp1.c"
"$WORK/gen" newamp1_energy_cb "$D/newamp1_energy_q.txt" \
    > "$C2/src/codebooknewamp1_energy.c"
"$WORK/gen" newamp2vq_cb "$D/codes_450.txt" > "$C2/src/codebooknewamp2.c"
"$WORK/gen" newamp2_energy_cb "$D/newamp2_energy_q.txt" \
    > "$C2/src/codebooknewamp2_energy.c"

# 5. sanity: every source the component's CMakeLists compiles is present.
MISSING=0
while read -r src; do
    [ -f "$DEST/$src" ] || { echo "codec2_prepare: missing $DEST/$src" >&2; MISSING=1; }
done < <(sed -n 's/^        "codec2\/codec2\/src\/\([A-Za-z0-9_]*\)\.c"/codec2\/codec2\/src\/\1.c/p' \
    "$(cd "$(dirname "$0")" && pwd)/../..//firmware_common/codec2/CMakeLists.txt")
[ "$MISSING" -eq 0 ]

echo "codec2 prepared at $C2 ($(find "$C2/src" -name '*.c' | wc -l) src files, commit ${C2_COMMIT:0:8})"
